# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34c140250ebc01b5c33f8897c026446a8f8b9424056752f344c95be9b9bcbad1b12a95f502fb277a8193563bdebae9e23412c1ce71eacb4e4d875e1c07b1a45d

test:
  secret_key_base: aac771b28cb0f4007815e23c3c2fdd399655562db7b208a8510971112d42d07a019498ba773fdfb59c7e7a8ec5a3754f1e06600784e1c4de8273e9ede103e867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
